server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: euraka-client-ad-spanor
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
#        预防bean的懒加载
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/imooc_ad_data?autoReconnect=true
    username: root
    password: stx123456
    tomcat:
      max-active: 8
      min-idle: 4
      initial-size: 2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
