server:
  port: 9000
spring:
  application:
    name: ad-gatway

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
zuul:
  prefix: /imooc
  routes:
    spansor:
      path: /ad-sponsor/**
      serviceId: euraka-client-ad-spanor
      #是否加前缀
      strip-prefix: false